// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function makeDispatch(state, reducer, interpreter, onNextState) {
  var dispatch = function (action) {
    var match = Curry._2(reducer, state, action);
    var nextEffect = match[1];
    Curry._1(onNextState, match[0]);
    if (nextEffect !== undefined) {
      return Curry._2(interpreter, Caml_option.valFromOption(nextEffect), dispatch);
    } else {
      return /* () */0;
    }
  };
  return dispatch;
}

var Reffect = {
  makeDispatch: makeDispatch
};

function setOrigin(param_0) {
  return /* SetOrigin */Block.__(0, [param_0]);
}

function setDestination(param_0) {
  return /* SetDestination */Block.__(1, [param_0]);
}

function setMinutes(param_0) {
  return /* SetMinutes */Block.__(2, [param_0]);
}

function fetchedRoute(param_0) {
  return /* FetchedRoute */Block.__(3, [param_0]);
}

function applyFetchAbility(stateEffect) {
  var state = stateEffect[0];
  var match = state.origin;
  var match$1 = state.destination;
  var match$2 = state.minutes;
  var routeFetchAbility = match !== undefined && match$1 !== undefined && match$2 !== undefined ? /* CanFetch */0 : /* CannotFetch */1;
  return /* tuple */[
          {
            origin: state.origin,
            destination: state.destination,
            minutes: state.minutes,
            routeFetchAbility: routeFetchAbility,
            dataLoadingState: state.dataLoadingState,
            routeDuration: state.routeDuration
          },
          stateEffect[1]
        ];
}

function directionsApi(origin, destination) {
  return "https://maps.googleapis.com/maps/api/directions/json?origin=" + (origin + ("&destination=" + (destination + "&key=AIzaSyC6AfIwElNGcfmzz-XyBHUb3ftWb2SL2vU")));
}

function canFetch(state) {
  var match = state.routeFetchAbility;
  if (match) {
    return false;
  } else {
    return true;
  }
}

function parseRoute(routeResponse) {
  return {
          duration: 5
        };
}

function behaviorInterpreter(networkRequest, effect, dispatch) {
  var actionCtor = effect[2];
  var api = directionsApi(effect[0], effect[1]);
  return Curry._2(networkRequest, api, (function (response) {
                return Curry._1(dispatch, Curry._1(actionCtor, 5));
              }));
}

function reducer(state, action) {
  var tmp;
  if (typeof action === "number") {
    tmp = action === /* FetchRoute */0 ? /* tuple */[
        {
          origin: state.origin,
          destination: state.destination,
          minutes: state.minutes,
          routeFetchAbility: state.routeFetchAbility,
          dataLoadingState: /* Loading */0,
          routeDuration: state.routeDuration
        },
        /* CalculateRoute */[
          Belt_Option.getExn(state.origin),
          Belt_Option.getExn(state.destination),
          fetchedRoute
        ]
      ] : /* tuple */[
        state,
        undefined
      ];
  } else {
    switch (action.tag | 0) {
      case /* SetOrigin */0 :
          tmp = /* tuple */[
            {
              origin: action[0],
              destination: state.destination,
              minutes: state.minutes,
              routeFetchAbility: state.routeFetchAbility,
              dataLoadingState: state.dataLoadingState,
              routeDuration: state.routeDuration
            },
            undefined
          ];
          break;
      case /* SetDestination */1 :
          tmp = /* tuple */[
            {
              origin: state.origin,
              destination: action[0],
              minutes: state.minutes,
              routeFetchAbility: state.routeFetchAbility,
              dataLoadingState: state.dataLoadingState,
              routeDuration: state.routeDuration
            },
            undefined
          ];
          break;
      case /* SetMinutes */2 :
          tmp = /* tuple */[
            {
              origin: state.origin,
              destination: state.destination,
              minutes: action[0],
              routeFetchAbility: state.routeFetchAbility,
              dataLoadingState: state.dataLoadingState,
              routeDuration: state.routeDuration
            },
            undefined
          ];
          break;
      case /* FetchedRoute */3 :
          tmp = /* tuple */[
            {
              origin: state.origin,
              destination: state.destination,
              minutes: state.minutes,
              routeFetchAbility: state.routeFetchAbility,
              dataLoadingState: state.dataLoadingState,
              routeDuration: action[0]
            },
            undefined
          ];
          break;
      
    }
  }
  return applyFetchAbility(tmp);
}

var fetchRoute = /* FetchRoute */0;

var noop = /* Noop */1;

var initialState = {
  origin: undefined,
  destination: undefined,
  minutes: undefined,
  routeFetchAbility: /* CannotFetch */1,
  dataLoadingState: /* NotLoading */1,
  routeDuration: undefined
};

exports.Reffect = Reffect;
exports.setOrigin = setOrigin;
exports.setDestination = setDestination;
exports.setMinutes = setMinutes;
exports.fetchRoute = fetchRoute;
exports.fetchedRoute = fetchedRoute;
exports.noop = noop;
exports.initialState = initialState;
exports.applyFetchAbility = applyFetchAbility;
exports.directionsApi = directionsApi;
exports.canFetch = canFetch;
exports.parseRoute = parseRoute;
exports.behaviorInterpreter = behaviorInterpreter;
exports.reducer = reducer;
/* No side effect */
